if: branch = master
language: go
go: 1.11
sudo: true # give us 7.5GB and >2 bursted cores.
git:
    depth: false
before_install:
    - git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
    - source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
    - source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
install:
    - source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
    - curl -L https://get.pulumi.com/ | bash -s -- --version 0.17.11-dev.1557787508
    - export PATH=$HOME/.pulumi/bin:$PATH
    # Install Helm
    - curl -o- -L https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
    - helm init -c
    - helm repo add bitnami https://charts.bitnami.com/bitnami
before_script:
    - ${PULUMI_SCRIPTS}/ci/ensure-dependencies
jobs:
    include:
        - script: make travis_${TRAVIS_EVENT_TYPE}
        - stage: latest
          if: type = cron
          script: ${GOPATH}/src/github.com/pulumi/scripts/ci/run-at-head
after_failure:
    - ${PULUMI_SCRIPTS}/ci/upload-failed-tests
notifications:
    webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
