exclude: "^.venv/.*|.html"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: trailing-whitespace
        exclude: ^VERSION.txt$
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        name: Run prettier on infra source code
        types_or: [ts]
  - repo: local
    hooks:
      - id: lockfile
        name: Update poetry.lock
        language: system
        entry: poetry lock --no-update
        files: ^pyproject.toml|poetry.lock$
        pass_filenames: false
      - id: version
        name: Update VERSION.txt -> pyproject.toml
        language: system
        entry: bash -c 'cat VERSION.txt | xargs poetry version'
        files: ^pyproject.toml|VERSION.txt$
        pass_filenames: false
      - id: requirements.txt
        name: Export app dependencies to app/requirements.txt
        language: system
        entry: poetry export -f requirements.txt --output app/requirements.txt
        files: ^pyproject.toml|poetry.lock$
        pass_filenames: false
      - id: isort
        name: Run isort on app source code
        language: system
        entry: poetry run isort
        types: [python]
        pass_filenames: true
      - id: black
        name: Run black on app source code
        language: system
        entry: poetry run black
        types: [python]
        pass_filenames: true
      - id: flake8
        name: Run flake8 on app source code
        language: system
        entry: poetry run flake8
        types: [python]
        pass_filenames: true
      - id: mypy
        name: Run mypy on app source code
        language: system
        entry: poetry run mypy
        types: [python]
        pass_filenames: false
